version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: next-db
      POSTGRES_PASSWORD: admin # Root 用户的密码
      POSTGRES_DB: next-db # 初始化数据库名称
    ports:
      - "5432:5432" # 映射 MySQL 的端口
    volumes:
      - postgres_data:/var/lib/postgresql/data # 数据持久化
    restart: unless-stopped

volumes:
  postgres_data:
